# Generated by Django 5.2.14 on 2026-05-22 19:58

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_pure_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region='RU', verbose_name='Нормализованный номер владельца'),
        ),
    ]
