# Generated by Django 5.2.14 on 2026-05-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_link_owners_with_flats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
